### ISSUE TITLE
Plugin error in Grafana 7.4

### ISSUE THREAD

**Issue by darioef** [jdbranham/grafana-diagram#184]
Hi,

After upgrading Grafana from 7.3.x to 7.4 some existing diagram panels show the following error in the top left corner:

`Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

![2021-02-09_17-59](https://user-images.githubusercontent.com/39913333/107427838-917d1d80-6b00-11eb-8dea-c274eb603ae1.png)

The only way to get it working again was duplicating the "good" panels and changing the queries/configuration to show the same data than the broken panels.

If you try to create a new dashboard with an empty Diagram Panel it shows the error too.

**How to reproduce it:**
It happens too installing a new instance of Grafana on Docker using the image version grafana/grafana:7.4.0, installing the 1.7.1 version of the Diagram Panel, creating a new dashboard and adding a Diagram panel.

Hope it helps.
Thanks.

**Comment by marcusolsson** [comment]
This is unfortunately due to an API breakage in Grafana 7.4. The Legend components used in this plugin should've been marked as internal by the Grafana team, as they weren't yet ready for the prime time. Instead they were exported, allowing plugin authors to discover, and to (rightfully) use them.

With https://github.com/grafana/grafana/pull/30165, these components were removed in favor of [VizLegend](https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-vizlegend--with-no-values). The error is a result of the plugin using components that have been removed.

I'll update this when as I learn more about how we can fix this.

**Comment by jdbranham** [comment]
Added an error boundary to at least allow rendering of diagram if the legend fails.  
It's a good place for a boundary anyway - and will allow folks to upgrade the plugin if they don't require the legend.

**Comment by ms-ai** [comment]
Would be great to be able to use 7.4 with your Diagram Plugin. Subscribing.

**Comment by BenLutin** [comment]
Would be great to be able to use 7.4 with your Diagram Plugin.
Thanks for your plugin & work !

**Comment by jdbranham** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/924

**Comment by jdbranham** [comment]
v1.7.3 restores Legend functionality for Grafana v7+. 
https://github.com/jdbranham/grafana-diagram/releases/tag/v1.7.3
