### ISSUE TITLE
Error with Grafana 7.5

### ISSUE THREAD

**Issue by davidnarayan** [jdbranham/grafana-diagram#195]
Using version 1.7.2 of this plugin with Grafana 7.5.5, I'm getting the following error:

```Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

This is without any configuration, just a new diagram dashboard panel. 

Perhaps related to #184

**Comment by yarix** [comment]
same problem here.
Using version 1.7.2 of this plugin with Grafana v7.5.4 (615c153b3a)
![image](https://user-images.githubusercontent.com/6409857/116855252-c1205b00-ac01-11eb-8e6b-90f439ab61e4.png)

**Comment by johankcarlsson** [comment]
Same problem with 1.7.2 of this plugin with Grafana v7.5.5.

**Comment by neub** [comment]
Same here with Grafana 7.4.5 and 1.7.2

**Comment by LyleLaii** [comment]
Same here with Grafana 7.4.3 (010f20c1c8) adn 1.7.2

**Comment by npdgm** [comment]
Did anyone find a workaround to get 1.7.x to run on Grafana 7.5.x ?
Cheers

**Comment by jdbranham** [comment]
I'm having trouble reproducing the error - 

There's an issue with 7.x and the Legend functionality, but it should show a message in the Legend area, rather than erring the  diagram render.  
Can you try disabling the Legend in the panel options to see if that avoids the error?  


You can see this is running 7.5.7 in the screenshot.  

![image](https://user-images.githubusercontent.com/2660839/120817551-69825180-c517-11eb-8b83-ff859db3222a.png)

**Comment by wilfriedroset** [comment]
I'm able to reproduce the error by doing the following step:
* `docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=jdbranham-diagram-panel" grafana/grafana:7.5.7`
* login with admin/admin (as its an empty container with the default image)
* create a new dashboard
* add an empty panel
* select diagram visualization (on the right)
* you should have the error

I can also confirm that with legend disabled the default diagram is displayed as expected

**Comment by jdbranham** [comment]
Sorry guys - I think I must have grabbed the wrong commit on the last publish, so the patch didn't make it in 😬 

I cherry picked @jackw  legend fixes from the 8x work [Thanks or the clean commits!]. 

I'll open another PR to get a v1.7.3 published, but my kids just walked in the door, so gotta sign-off for a bit 😅

**Comment by jdbranham** [comment]
Since `VizLegend` is not available until `Grafana v7.4.0` - it's the new minimum version for `Diagram v1.7.3`   

For Grafana versions `>= 7.0  AND < 7.4` disabling the Legend in the Diagram options is a workaround.   
I hope that works for everyone.   
If you're on Grafana `v7.3.x` and are unable to upgrade, let me know and I'll try to release a patch.  Otherwise upgrading Grafana is the best option.

**Comment by jdbranham** [comment]
PR opened for publishing to Grafana -  
https://github.com/grafana/grafana-plugin-repository/pull/964

**Comment by jdbranham** [comment]
If you're using docker and don't want to wait for .com publishing, you can use the download url.    

```
docker run --rm \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_INSTALL_PLUGINS=https://github.com/jdbranham/grafana-diagram/releases/download/v1.7.3/jdbranham-diagram-panel-1.7.3.zip;jdbranham-diagram-panel" \
  grafana/grafana:7.4.0
```
