### ISSUE TITLE
Subgraph characteristics

### ISSUE THREAD

**Issue by zenmetsu** [jdbranham/grafana-diagram#38]
I could not find much help in the docs or on the mermaid js site regarding this request.

Is there a way to color the subgraphs?  Currently they are a shade of green and I cannot figure out how to change this.  Ideally, it could be a gradient based upon a metric.

Also, is there a way to change the default shape of a subgraph, for example use a circle?

**Comment by jdesgats** [comment]
I hit the same issue: it is caused by a `!important` tag in the [SCSS file](https://github.com/jdbranham/grafana-diagram/blob/4de18d716af0a713b1b03fe27a7825fefa4a4217/src/css/diagram.scss#L106). This takes precedence over the inline style that doesn't have this tag.

For instance here, the inline style is set to red, but the subgraph still appear green:
![image](https://user-images.githubusercontent.com/849031/63839550-6e47c800-c977-11e9-97ba-67130e4c8917.png)

**Comment by danielmotaleite** [comment]
i'm also having this problem! :(
Is there any workaround? using the custom styles maybe?

about the subgraph shape, mermaid documentation say anything about it, so you probably can't change it

**Comment by jdbranham** [comment]
The custom styles might work. I don't think this hasn't been tested since that feature was added.

**Comment by jdbranham** [comment]
Lots of new styling options in v1.7+ of the plugin
