### ISSUE TITLE
Text shadows

### ISSUE THREAD

**Issue by pesutak** [jdbranham/grafana-diagram#78]
Hello, is there a way to disable or fix text shadows? in chrome the shadows are very unnatural
Thanks

![image](https://user-images.githubusercontent.com/25058940/33959240-25a26562-e047-11e7-8543-942a31e89943.png)

**Comment by briangann** [comment]
do you have sample mermaidjs content that does this? I'm not seeing shadows in chrome.  It looks like you have some extra css being loaded from the screenshot.

**Comment by scaarup** [comment]
Same annoying issue here. But it is very easy to see where it's set - see screenshot.
With zoom-level 100%, it's not really an issue. We discovered it because we are using the diagram plugin on our 65" big screen with a chromebook. And I can reproduce it on my mac by zooming in on the chrome browser.
<img width="1885" alt="screenshot 2018-12-27 at 13 54 55" src="https://user-images.githubusercontent.com/8055470/50480914-18351600-09df-11e9-8234-1af81cc6939f.png">
<img width="294" alt="screenshot 2018-12-27 at 13 54 40" src="https://user-images.githubusercontent.com/8055470/50480915-18351600-09df-11e9-842a-18faa5a1abab.png">
