### ISSUE TITLE
Composite Metric Evalution for Binary Metrics

### ISSUE THREAD

**Issue by thehorseman1976** [jdbranham/grafana-diagram#95]
Greetings.

I have encountered an curious issue with the plugin.  I have successfully created a Diagram panel that monitors the STATUS of several printers, P1, P2, P3, P4, etc. The value that comes from Zabbix is either 0 (offline) or 1(online).  I have a diagram element element called PRINTERS which is a composite for the STATUS of each printer being monitored.

After setting the thresholds to [0.1,1] with colors (Red, Yellow, Green), each "node" is correctly displayed as far as its individual color goes, but the composite node does to.  

Example:

For P1(1), P2(1), P3(0)

I get P1(Green), P2(Green), P3(Red)
but my composite, shows as PRINTERS(Green) (with a value of 1), when it should be RED.

Inverting the colors did not solve the problem as it only changed the colors but not the way they were being evaluated.

I suspect this has something to with the logic of what the composite evaluation considers to be the "worse" metric, always taking into account the larger value.  Which makes sense as what is normally monitored as far as systems go tend to be "worse" the higher the value (i.e. RAM usage, connected users, traffic, etc.).  When I use the plugin for items like those mentioned above, the Diagram works fine and the Composite works as expected.

Is this something that can be worked around within the plugins parameters or something that would have to be added in a future update?

The only workaround that I can see for now is along the lines of "cloning" my item in Zabbix and having it return the inverse (0 when online, 1 when offline) so that it'll always consider the higher value, now 1, to be the "worst".

Any insight would be greatly appreciated.

**Comment by briangann** [comment]
Additional logic will be needed.  A state "direction" (ascending/descending) or state ranges needs to be added.

The same issue exists with Sensu, where state = 3 is "unknown" which may not be "worse" than "critical". 

I'll put in a PR with a fix for this asap.

**Comment by thehorseman1976** [comment]
Thank you very much!  This will be a very welcome addition!

**Comment by samard** [comment]
@briangann ...please share any chance of having this feature getting released sooner.
I was working on an Application availability architecture diagram, but due to this issue of not taking lower value (0=DOWN, 1=UP) as Worst/critical case, I had to switch from Diagram to Polystat plugin. Though Diagram suits more for an architecture-wise status panel.

**Comment by zsabin** [comment]
I saw the new "show lowest" option available on metric composites, but this is still inadequate for some of my use cases, since I sometimes have composites that contain both ascending and descending thresholds. It would be much better to be able to specify the direction of the threshold at the series level, rather than at the composite level. The composites would then determine 'worst' on a series-by-series basis. That way I could simply invert the colors for all series with descending thresholds.
